# Generated by Django 2.2.5 on 2019-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('year', models.DateTimeField()),
                ('client', models.CharField(max_length=255, null=True)),
                ('Description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/works/')),
            ],
        ),
    ]
