# Generated by Django 2.2.5 on 2019-09-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='Description',
            new_name='description',
        ),
    ]
