# Generated by Django 2.2.5 on 2019-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_front', '0002_auto_20190916_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
